[tool.poetry]
name = "ree-connector"
version = "0.1.3"
description = "Lightweight package to consume data from REE (Red Eléctrica de España)"
authors = ["Jorge Marín <jormarcor@alum.us.es>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = ""
documentation = "https://jorgemarin.gitlab.io/ree-connector/"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
keywords = [
    "Python",
    "Energy",
    "Tools",
    "IoT",
    "Domotics"
]
exclude = ["tests"]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
