[tool.poetry]
name = "boka-tools"
version = "0.2.0"
description = "package for general automation work at Boskalis"
authors = ["Maarten Betman <maarten.betman@boskalis.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
pandas = "^1.3.4"
SQLAlchemy = "1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
